install.packages("remotes")
remotes::install_github("rjdverse/rjd3toolkit@*snapshot")
remotes::install_github("palatej/rjd3sax")
remotes::install_github("rjdverse/rjd3sts@*release")
remotes::install_github("rjdverse/rjd3tramoseats@*release")
